"""added deleted column

Revision ID: 185104ae48aa
Revises: a25013890482
Create Date: 2019-03-10 12:25:51.277415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185104ae48aa'
down_revision = 'a25013890482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'deleted')
    # ### end Alembic commands ###
